export type * from "./especie";
export type * from "./common";
export type * from "./dashboard";
export type * from "./empleado";
export type * from "./tratamiento";
export type * from "./necropsias";
export type * from "./zona";
export type * from "./animal";
export type * from "./account";
export type * from "./habitat";
export type * from "./settings"
export type * from "./alimentacion"
export type * from "./comportamiento";
