using feedback_zoologic.Features.Especies.Application;
using feedback_zoologic.Features.Especies.Application.Common;
using feedback_zoologic.Features.Especies.Infraestructure.Models;

namespace feedback_zoologic.Features.Especies.Application
{
    public interface IEspecieQueryRepository
    {
        //Task<EspecieResponse> GetByIdAsync(int epecieId, CancellationToken cancellationToken = default);
        //Task<IEnumerable<EspecieResponse>> GetAllAsync(CancellationToken cancellationToken = default);
        //Task<int> UpdateAsync(EspecieResponse especie, CancellationToken cancellationToken);
    }
}